version: "3"
services:
  api:
    build: .
    volumes: 
      - ./library:/app/library
    working_dir: /app/library
    ports: 
      - "8000:8000"
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_READ_ENV_FILE=true
